### ISSUE TITLE
code for visualizing the loss landscape

### ISSUE THREAD

**Issue by d12306** [shuyao95/Understanding-NAS#1]
Hi, @shuyao95 , thanks for yout implementation and do you have the code for loss landscape visualization?

Thanks,

**Comment by shuyao95** [comment]
Hi @d12306, thanks for your interest in our codes. The visualization code is based on https://github.com/tomgoldstein/loss-landscape, including the codes for loss landscape and gradient variance. You can simply adapt their codes to reproduce the results shown in our paper.

**Comment by d12306** [comment]
@shuyao95 ， hi，sorry for bothering again, but there are so many weights in a model, do you obtain the gradient for each weight, average them and finally get one value for each set of weight (similar to the loss value) and plot it?

**Comment by shuyao95** [comment]
Hi @d12306, I think you are trying to get the plots of gradient variance. For this one, our paper has provided the computation of gradient variance regarding the whole model parameters. Specifically, it's the expectation of Frobenius norm on the difference between gradient and expected gradient over the whole dataset. BTW, the whole model parameters are treated as a vector, which is similar to the piloting of loss landscape.

**Comment by d12306** [comment]
@shuyao95 , yes, so the expected gradient is the one computed using one batch and the real gradient is the gradient computed using one sample, right? and you iterative over N times (N is the batch size) to compute the difference?

**Comment by shuyao95** [comment]
The expectation of gradient is over the whole dataset. To achieve higher computational efficiency, we take the gradient of all batches to compute the expectation instead of the one from single sample.

**Comment by d12306** [comment]
@shuyao95 , thanks for your clarification.
